git:
    depth: 10

language: php

php:
    - '7.1'
    - '7.2'

cache:
    directories:
        - $HOME/.composer/cache

install:
    - sudo apt-get update
    - sudo apt-get install libgearman-dev -y --no-install-recommends --no-install-suggests
    - export GEARMAN_PACKAGE=gearman-2.0.3
    - curl -L -O https://github.com/wcgallego/pecl-gearman/archive/$GEARMAN_PACKAGE.tar.gz
    - tar zxvf $GEARMAN_PACKAGE.tar.gz
    - pushd pecl-gearman-$GEARMAN_PACKAGE
    - phpize
    - ./configure
    - make
    - make install
    - echo 'extension=gearman.so' > gearman.ini
    - phpenv config-add gearman.ini
    - popd
    - composer self-update
    - composer install --prefer-source

script:
    - vendor/bin/phpunit --exclude-group=functional
